### ISSUE TITLE
Chrome and Chromium not responding after sleep

### ISSUE THREAD

**Issue by pavliha** [RichJack/Chromixium#11]

**Comment by RichJack** [comment]
I'm going to need some more detail than this I'm afraid if I cam going to be able to investigate. I use sleep mode a lot on my laptop and never have this problem:
Version of Chromixium and 32 or 64 bit?
Your computer hardware specs - make/model/processor/graphics etc...
Whether other applications are also unresponsive?
If you don't have Chrome/Chromium already running when you enter sleep, will they open afterwards?
Thanks

**Comment by pavliha** [comment]
Chromixium 64 bit
Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz
Nvidia GFORCE 550TI
Other applications work fine.
Whether Chrome running or not, after sleep Chrome won't open afterwards. Same is for Chromium too.

**Comment by RichJack** [comment]
You are not alone:
https://code.google.com/p/chromium/issues/detail?id=241013

No solution there though. Can you disable hardware acceleration from Chrome settings\advanced settings please and test.

Also, are you using open source Nvidia nouveau drivers or proprietary Nvidia drivers? Have you tried it on each driver setup?

**Comment by pavliha** [comment]
Tried. Solved the problem. Thanks

**Comment by RichJack** [comment]
Great, thanks for letting us know, closing issue.
