### ISSUE TITLE
Change window border colour

### ISSUE THREAD

**Issue by k4r7u** [RichJack/Chromixium#4]
I changed the window borders to gray, similar to the gray used in the close-window-icon.
In my opinion this provides a sleeker user interface.
![image](https://cloud.githubusercontent.com/assets/8782287/6482306/c14ad5c0-c264-11e4-94a9-01fc50bba8a8.png)

**Comment by RichJack** [comment]
I've got someone working on the theme as we speak so I'll pass this suggestion onto them. Thanks.

**Comment by thenoncoder** [comment]
Material design is better than this grey thing imo.

**Comment by RichJack** [comment]
Yeah we'll probably go blue in future, but material design is not just about color as such, it's about clarity of symbolism and use of shadows and 3D effects. This original theme was copied from Chromium OS before material design really took hold. So it will be ready for an overhaul come Chromixium 2.0

**Comment by crutchcorn** [comment]
My original intention was to be gray, however I ran out of time - life began - and I left it as you see today. If you'd like, I'd love a pull request on the GTK theme found here @k4r7u :  
https://github.com/crutchcorn/chromeostheme

Secondly @thenoncoder: I have considered starting a Material Design GTK theme based on EvoPop (simply because EvoPop rules) but I've been trying to mimic ChromeOS' theme

**Comment by thenoncoder** [comment]
@crutchcorn *EvoPop* is too much skeumorphic.
Material design is a ton better.

**Comment by crutchcorn** [comment]
@thenoncoder EvoPop (I'm not going to argue which is better, everyone has a right to see things the way they do), while more skeumorphic and different, is similar-ish to MD. At lease when you consider the colouring (which uses the MD colour palette) and such. I would know as I was part of the EvoPop team (though I only did a few icons). I know that there are some that do not like EvoPop, however I will try my best to modify the GTK theme to match the qualities of MD

**Comment by k4r7u** [comment]
@crutchcorn : Pull request is created.

**Comment by crutchcorn** [comment]
@k4r7u Already closed. :)

**Comment by crutchcorn** [comment]
@RichJack You might want to close this issue

**Comment by k4r7u** [comment]
pull request merged.
