### ISSUE TITLE
Double clicking opens two windows

### ISSUE THREAD

**Issue by viktorahlstrom** [RichJack/Chromixium#5]

**Comment by DennisLfromGA** [comment]
Then use a 'single-click' for one window. ;-)

No really, is this a 'crouton' question? What is it you're clicking on?

**Comment by viktorahlstrom** [comment]
Sorry - probably should have asked somewhere else, but when I'm in control panel, if I double click one of the icons, like "Bluetooth Manager", it will open two windows.

**Comment by DennisLfromGA** [comment]
No problem, that is the normal 'Control Panel' behavior and I don't know if it can be changed.
I often change the File manager's 'File Preferences/Behavior' to use 'Single click to open items' but that's just my preference.

**Comment by viktorahlstrom** [comment]
Okay - thanks.
