### ISSUE TITLE
Error when trying to add a new user

### ISSUE THREAD

**Issue by possnfiffer** [RichJack/Chromixium#8]
I want to create a new user account for my schooling. 

Chromixium is awesome! Thanks. I'm running 1.5 amd64

Sofar, I've tested multiple users in Chrome and the initial account that I sign in with becomes the account that all the buttons in the main Chromixium menu bar open with. I find no easy way to control the accounts. I figured there would be a way to easily switch the "active" account for these buttons like you do in the Chrome App Launcher menu.

To solve this, the new user account. When I finished adding the account details and confirmed creating the account, I got an error. I have a screenshot.

![screenshot from 2015-11-09 19 48 36](https://cloud.githubusercontent.com/assets/773239/11053184/23363d02-871c-11e5-97d9-34796b3f336c.png)

**Comment by RichJack** [comment]
Have you rebooted and attempted the create new user process again? It looks like the add user applet hasn't requested your sudo password resulting in the error. When you add a user, it should request your password. You must have sudo access.

You can also add a new user in a terminal and then follow the prompts:
`sudo adduser <new user name>`

**Comment by possnfiffer** [comment]
Yeah. I'm on another Chromixium machine (I got it running on an old MacPro 3,1 - so fast! )

I tried it just now on this machine, same issue. Looks like the Users and Groups applet isn't requesting sudo permissions.

**Comment by possnfiffer** [comment]
I checked and verified that I do have sudo on my user account.

Here's a recording of the issue

https://drive.google.com/file/d/0B2SQD9iDJq72b3QwYk9naC05M00/view?usp=sharing

**Comment by DennisLfromGA** [comment]
@possnfiffer - Are you using a 'space' character in the username ? If so, try it without a space.

**Comment by possnfiffer** [comment]
Trying to add with a . like this

user.name

**Comment by RichJack** [comment]
A clean install of amd64 1.5 in a test VM and when I click Add in the Users applets, I get prompted for my sudo password immediately. If you wait too long before authenticating then it might time out. Close the applet and start again. I had no problems creating a test user account, but it didn't like a dot in the username. Can you first try without a dot please?

I believe by default adding a dot is banned on Ubuntu systems:
http://askubuntu.com/questions/307225/what-is-the-logic-behind-the-user-name-restrictions-in-buntu

**Comment by possnfiffer** [comment]
It doesn't like the dot. I tried without it and it's working fine. Thanks =D
